"""create survey tables

Revision ID: 5768d368f630
Revises: d277b2e9b63e
Create Date: 2026-10-02 14:34:18.547313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5768d368f630'
down_revision: Union[str, Sequence[str], None] = 'd277b2e9b63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_versions',
    sa.Column('survey_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('survey_type', sa.Enum('initial_lifestyle', 'interim_lifestyle', 'sodium', name='survey_type'), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('survey_version_id'),
    sa.UniqueConstraint('survey_type', 'version')
    )
    op.create_table('survey_questions',
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('survey_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_code', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_versions.survey_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('survey_version_id', 'question_code')
    )
    op.create_table('survey_instances',
    sa.Column('survey_instance_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('survey_version_id', sa.CHAR(length=36), nullable=False),
    sa.Column('health_record_id', sa.CHAR(length=36), nullable=True),
    sa.Column('status', sa.Enum('started', 'submitted', 'abandoned', name='survey_instance_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.health_record_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_version_id'], ['survey_versions.survey_version_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('survey_instance_id')
    )
    op.create_index(op.f('ix_survey_instances_user_id'), 'survey_instances', ['user_id'], unique=False)
    op.create_table('survey_options',
    sa.Column('option_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('option_code', sa.String(length=50), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.Column('numeric_score', sa.Numeric(precision=8, scale=2, asdecimal=False), nullable=True),
    sa.Column('model_value_code', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id'),
    sa.UniqueConstraint('question_id', 'option_code')
    )
    op.create_table('survey_responses',
    sa.Column('response_id', sa.CHAR(length=36), nullable=False),
    sa.Column('survey_instance_id', sa.CHAR(length=36), nullable=False),
    sa.Column('question_id', sa.CHAR(length=36), nullable=False),
    sa.Column('option_id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['survey_options.option_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.question_id'], ),
    sa.ForeignKeyConstraint(['survey_instance_id'], ['survey_instances.survey_instance_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('survey_instance_id', 'question_id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('survey_responses')
    op.drop_table('survey_options')
    op.drop_index(op.f('ix_survey_instances_user_id'), table_name='survey_instances')
    op.drop_table('survey_instances')
    op.drop_table('survey_questions')
    op.drop_table('survey_versions')
    # ### end Alembic commands ###
