"""create health tables

Revision ID: 998b0ee91444
Revises: af07c07b18dd
Create Date: 2026-10-02 11:07:49.642791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '998b0ee91444'
down_revision: Union[str, Sequence[str], None] = 'af07c07b18dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_input_schemas',
    sa.Column('health_schema_id', sa.CHAR(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('model_scope', sa.Enum('MODEL_A', 'MODEL_B', 'BOTH', 'TRACKING', name='model_scope_type'), nullable=False),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('health_schema_id'),
    sa.UniqueConstraint('schema_version')
    )
    op.create_table('health_records',
    sa.Column('health_record_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('health_schema_id', sa.CHAR(length=36), nullable=False),
    sa.Column('cycle_id', sa.CHAR(length=36), nullable=True),
    sa.Column('input_type', sa.Enum('initial', 'interim_reassessment', 'full_reassessment', 'weekly_bp', 'manual', name='health_input_type'), nullable=False),
    sa.Column('source_type', sa.Enum('manual', 'ocr', 'mixed', name='health_source_type'), nullable=False),
    sa.Column('examination_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['health_schema_id'], ['health_input_schemas.health_schema_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('health_record_id'),
    sa.UniqueConstraint('user_id', 'input_type', 'examination_date')
    )
    op.create_index(op.f('ix_health_records_user_id'), 'health_records', ['user_id'], unique=False)
    op.create_table('health_measurements',
    sa.Column('measurement_id', sa.CHAR(length=36), nullable=False),
    sa.Column('health_record_id', sa.CHAR(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=50), nullable=False),
    sa.Column('value_num', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('value_code', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('input_method', sa.Enum('manual', 'ocr', 'calculated', 'carried_forward', name='measurement_input_method'), nullable=False),
    sa.Column('source_measurement_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['health_record_id'], ['health_records.health_record_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_measurement_id'], ['health_measurements.measurement_id'], ),
    sa.PrimaryKeyConstraint('measurement_id'),
    sa.UniqueConstraint('health_record_id', 'metric_code')
    )
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('active', 'deleted', 'pending_guardian'),
               type_=sa.Enum('active', 'deleted', 'panding_guardian', name='user_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('active', 'deleted', 'panding_guardian', name='user_status'),
               type_=mysql.ENUM('active', 'deleted', 'pending_guardian'),
               existing_nullable=False)
    op.drop_table('health_measurements')
    op.drop_index(op.f('ix_health_records_user_id'), table_name='health_records')
    op.drop_table('health_records')
    op.drop_table('health_input_schemas')
    # ### end Alembic commands ###
