"""create guardian_consent_verifications

Revision ID: af07c07b18dd
Revises: 18845fa6e977
Create Date: 2026-10-01 18:39:33.938995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af07c07b18dd'
down_revision: Union[str, Sequence[str], None] = '18845fa6e977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_consent_verifications',
    sa.Column('guardian_verification_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('guardian_name_enc', sa.String(length=500), nullable=True),
    sa.Column('guardian_relation', sa.Enum('parent', 'legal_guardian', name='guardian_relation'), nullable=False),
    sa.Column('guardian_contact_enc', sa.String(length=500), nullable=True),
    sa.Column('verification_method', sa.Enum('sms', 'email', name='verification_method'), nullable=False),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'expired', 'purged', name='guardian_verification_status'), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('purge_due_at', sa.DateTime(), nullable=False),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guardian_verification_id')
    )
    op.create_index(op.f('ix_guardian_consent_verifications_purge_due_at'), 'guardian_consent_verifications', ['purge_due_at'], unique=False)
    op.create_index(op.f('ix_guardian_consent_verifications_user_id'), 'guardian_consent_verifications', ['user_id'], unique=False)
    op.alter_column('users', 'status',
               existing_type=mysql.ENUM('active', 'deleted', 'pending_guardian'),
               type_=sa.Enum('active', 'deleted', 'pending_guardian', name='user_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('active', 'deleted', 'pending_guardian', name='user_status'),
               type_=mysql.ENUM('active', 'deleted', 'pending_guardian'),
               existing_nullable=False)
    op.drop_index(op.f('ix_guardian_consent_verifications_user_id'), table_name='guardian_consent_verifications')
    op.drop_index(op.f('ix_guardian_consent_verifications_purge_due_at'), table_name='guardian_consent_verifications')
    op.drop_table('guardian_consent_verifications')
    # ### end Alembic commands ###
