"""survey number answers

Revision ID: c9429b68803a
Revises: 0e62093ddb61
Create Date: 2026-10-08 12:21:31.111075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9429b68803a'
down_revision: Union[str, Sequence[str], None] = '0e62093ddb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_questions', sa.Column('answer_type', sa.Enum('single_select', 'number', name='survey_answer_type'), server_default='single_select', nullable=False))
    op.add_column('survey_questions', sa.Column('num_min', sa.Integer(), nullable=True))
    op.add_column('survey_questions', sa.Column('num_max', sa.Integer(), nullable=True))
    op.add_column('survey_responses', sa.Column('value_num', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True))
    op.alter_column('survey_responses', 'option_id',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('survey_responses', 'option_id',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    op.drop_column('survey_responses', 'value_num')
    op.drop_column('survey_questions', 'num_max')
    op.drop_column('survey_questions', 'num_min')
    op.drop_column('survey_questions', 'answer_type')
    # ### end Alembic commands ###
